[package]
name = "dllm-sc"
version = "1.0.0"
authors = []

[addresses]
"dllm_addr" = "0xdaa36db121c34bb7aa2b095b4c1d7938e44cd0863a354ed0c8f9b42ee270de66"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
