[package]
name = "dllm-sc"
version = "1.0.0"
authors = []

[addresses]
"dllm_addr" = "0x9123e2561d81ba5f77473b8dc664fa75179c841061d12264508894610b9d0b7a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
